core:
  - changed-files:
      - any-glob-to-any-file:
          - "lunimago/core/**/*"

games:
  - changed-files:
      - any-glob-to-any-file:
          - "lunimago/games/**/*"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**/*"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - ".github/labeler.yml"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "docs/**/*"

build:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - ".github/workflows/release.yml"
          - ".github/workflows/auto-tag.yml"
