# Auto-label PRs based on changed files

core:
  - changed-files:
      - any-glob-to-any-file: 'lungula/core/**'

games:
  - changed-files:
      - any-glob-to-any-file: 'lungula/games/**'

tests:
  - changed-files:
      - any-glob-to-any-file: 'tests/**'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'
      - any-glob-to-any-file: '.github/labeler.yml'

docs:
  - changed-files:
      - any-glob-to-any-file: '*.md'
      - any-glob-to-any-file: 'docs/**'

build:
  - changed-files:
      - any-glob-to-any-file: 'pyproject.toml'
      - any-glob-to-any-file: '.github/workflows/release.yml'
      - any-glob-to-any-file: '.github/workflows/auto-tag.yml'
